Specs
Miguelus373/Ruby-Tic-Tac-Toe pull request #7
Opened 2020-09-11 17:20 UTC by Miguelus373

### What this PR does

- Adds rspec files 
- Adds test files for the logic.rb and board.rb files
- Tests these files using the Rspec TDD

2020-09-11 23:04 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [x] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Lets test the method in the class below
````ruby
class Message
  def initialize(message)
    @message = message
  end

  def display
    yield('*' * 40)
    yield(@message)
    yield('*' * 40)
  end
end

````
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-12 00:03 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job guys :clap: :+1: :100: you are almost there, we need here just some final touches to get your project approved :checkered_flag: 

- [x] Change the name of the gemfile file to Gemfile, cause it goes with uppercase, also add the rspec gem in the file so other developers wouldn't have to install the RSpec globally

- [x] Add some test for the Message class as required by the previous TSE.

- [ ] Add to the readme file how to run the tests and what's the requirements for it.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2020-09-12 00:03 UTC, elmejdki commented on spec/logic_spec.rb
> +  game_incomplete = Logic.new(['X', 'O', 'X', 'X', 5, 6, 7, 8, 9])
please use let to declare new variables instead of declaring them directly like this, you can check the [documentation](https://github.com/rubocop-hq/rspec-style-guide#let-blocks) for more syntax info

```ruby

let(:tree) { Tree.new(1 => 2, 2 => 3, 2 => 6, 3 => 4, 4 => 5, 5 => 6) }

it 'finds shortest path' do
  expect(dijkstra.shortest_path(tree, from: 1, to: 6)).to eq([1, 2, 6])
end
```

2020-09-12 00:03 UTC, elmejdki commented on spec/logic_spec.rb
> +    game_not_win = Logic.new([1, 2, 3, 'O', 'X', 6, 7, 8, 'X'])
please use let to declare new variables instead of declaring them directly like this, you can check the [documentation](https://github.com/rubocop-hq/rspec-style-guide#let-blocks) for more syntax info

```ruby

let(:tree) { Tree.new(1 => 2, 2 => 3, 2 => 6, 3 => 4, 4 => 5, 5 => 6) }

it 'finds shortest path' do
  expect(dijkstra.shortest_path(tree, from: 1, to: 6)).to eq([1, 2, 6])
end
```

2020-09-12 00:03 UTC, elmejdki commented on spec/board_spec.rb
> +  board = Board.new([1, 2, 3, 4, 5, 6, 7, 8, 9])
please use let to declare new variables instead of declaring them directly like this, you can check the [documentation](https://github.com/rubocop-hq/rspec-style-guide#let-blocks) for more syntax info

```ruby

let(:tree) { Tree.new(1 => 2, 2 => 3, 2 => 6, 3 => 4, 4 => 5, 5 => 6) }

it 'finds shortest path' do
  expect(dijkstra.shortest_path(tree, from: 1, to: 6)).to eq([1, 2, 6])
end
```

2020-09-12 00:03 UTC, elmejdki commented on spec/board_spec.rb
> +require './lib/board.rb'
**[OPTIONAL]** Using require_relative for files in your directory instead of require is a ruby convention.

2020-09-12 00:03 UTC, elmejdki commented on spec/logic_spec.rb
> +require './lib/logic.rb'
**[OPTIONAL]** Using require_relative for files in your directory instead of require is a ruby convention.

2020-09-12 08:09 UTC, kitpao requested changes
# 👋 Hello @Miguelus373 and @carlos-ssh 

🌟 Great job with your specs! You are almost done, there are still some technical details that you need to fix before continuing, please check them below ⬇️ 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- [ ] I see you tried to add the file to your .gitignore as requested, but for it is still displaying in the .github folder, the cause is most likely because there should be a dot (.) at the beginning of the name `.DS_Store` 📝 Remember the steps are: 
  * In your local, copy the .DS_Store file and put it somewhere else outside your repo
  * Delete .DS_Store file from repo
  * commit and push your changes
  * Then, you can return the copied file to your repo and it will be ignored by git

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate if can leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😛 

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-09-12 08:09 UTC, kitpao commented on spec/message_spec.rb
> +      expect(message.display { |i| p i }).to eql('****************************************')
- [x] Your tests print some debugging code, please delete it. **hint** you can do this by taking out the `p`, rspec doesn't need to actually print the result so you can leave it as `{ |i| i }`
![image](https://user-images.githubusercontent.com/53256139/92990653-cfb7d780-f4a3-11ea-84d3-c8fc18c4f1b1.png)
![image](https://user-images.githubusercontent.com/53256139/92990627-8cf5ff80-f4a3-11ea-9fe0-5fcea15eddf5.png)

2020-09-12 08:09 UTC, kitpao commented on README.md
> +### How to run the cases
- [ ] **OPTIONAL** To be more clear, you can specify "How to run the **test** cases"

2020-09-12 08:09 UTC, kitpao commented on README.md
> +- Once you have the repo just run `rspec` in the command line
- [ ] Well before using the `rspec` command, the user needs to run `bundle install` to get the necessary gems, please just add that instruction. **Extra tip:** If you want to see how your project looks like for others, you can use a virtual environment in Gitpod by appending `gitpod.io/` to the URL of your repo-branch: https://gitpod.io/github.com/Miguelus373/Ruby-Tic-Tac-Toe/tree/specs

2020-09-12 20:38 UTC, euqueme approved these changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @Miguelus373 :lollipop: 

### You've done amazing work with your test cases and your repository they are both looking very professional, thank you for applying all the changes requested by the previous reviewers :1st_place_medal:  is a yes for me :clap: :clap: :clap: you may merge this branch and move on Congratulations!! :smiley:  :tada: :tada: :tada: 

## [OPTIONAL]

- [ ] For your negative test cases instead of using `.to be` or `.to eql` for convention you should use `.not_to be` or `.not_to eql` and change the description to a negative one for example:

change this
```ruby
    it 'returns false when invalid move' do
      expect(move_board.move(0, 'O')).to be false
    end
```
to this:
```ruby
    it "doesn't return true when invalid move" do
      expect(move_board.move(0, 'O')).not_to be true
    end
```
### Keep up the good work :clinking_glasses: 

PROJECT STATUS: APPROVED :green_apple:

2020-11-26 22:30 UTC, merged